var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-state borders
		'lakesColor':'#ACE9FC', // lakes color
		'namesColor':'#919191', //color of short names
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ALABAMA', //state hover content
		'url':'javascript:void(0)', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#EBECED', //state's color when page loads
		'overColor':'#FFEE88', //state's color when mouse hover
		'downColor':'#FFEE88',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'ALASKA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_3':{
		'hover': 'ARIZONA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': 'ARKANSAS',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		'hover': 'CALIFORNIA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': 'COLORADO',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		'hover': 'CONNECTICUT',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		'hover': 'DELAWARE',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_9':{
		'hover': 'FLORIDA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_10':{
		'hover': 'GEORGIA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_11':{
		'hover': 'HAWAII',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': 'IDAHO',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': 'ILLINOIS',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		'hover': 'INDIANA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		'hover': 'IOWA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		'hover': 'KANSAS',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		'hover': 'KENTUCKY',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_18':{
		'hover': 'LOUISIANA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_19':{
		'hover': 'MAINE',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_20':{
		'hover': 'MARYLAND',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		'hover': 'MASSACHUSETTS',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_22':{
		'hover': 'MICHIGAN',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		'hover': 'MINNESOTA',
		'url':'http://www.caare.org/Minnesota',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		'hover': 'MISSISSIPPI',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_25':{
		'hover': 'MISSOURI',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_26':{
		'hover': 'MONTANA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		'hover': 'NEBRASKA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		'hover': 'NEVADA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_29':{
		'hover': 'NEW HAMPSHIRE',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		'hover': 'NEW JERSEY',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_31':{
		'hover': 'NEW MEXICO',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_32':{
		'hover': 'NEW YORK',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_33':{
		'hover': 'NORTH CAROLINA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_34':{
		'hover': 'NORTH DAKOTA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		'hover': 'OHIO',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		'hover': 'OKLAHOMA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_37':{
		'hover': 'OREGON',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_38':{
		'hover': 'PENNSYLVANIA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_39':{
		'hover': 'RHODE ISLAND',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_40':{
		'hover': 'SOUTH CAROLINA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_41':{
		'hover': 'SOUTH DAKOTA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#FFEE88',
		'enable':true,
	},
	'map_42':{
		'hover': 'TENNESSEE',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_43':{
		'hover': 'TEXAS',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_44':{
		'hover': 'UTAH',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_45':{
		'hover': 'VERMONT',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_46':{
		'hover': 'VIRGINIA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_47':{
		'hover': 'WASHINGTON',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_48':{
		'hover': 'WEST VIRGINIA',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_49':{
		'hover': 'WISCONSIN',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_50':{
		'hover': 'WYOMING',
		'url':'javascript:void(0)',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
}
